### ISSUE TITLE
tracking issue: array API standard document

### ISSUE THREAD

**Issue by rgommers** [data-apis/array-api#27]
**Timeline (high-level)**

- Aug 31: array RFC draft complete enough for final internal review
- Sep 15: array RFC published + array-api repo public

**Array API standard document intermediate steps**:

_Aug 10_:

- [x] Broadcasting (_status: merged_)
- [x] Mutability (_status: pending discussion, see https://github.com/data-apis/array-api/issues/24_)
- [x] Dtypes and casting (_status: merged_)
- [x] API signatures: statistical reductions (_status: merged_)
  
_Aug 17_:

- [x] Purpose and scope (_status: scope part (gh-22) merged, "how to adopt" (gh-33) under review_)
- [x] Type signatures (_status: merged_)
- [x] Static typing (_status: gh-62 for review_)
- [x] Indexing (_status: under review_)
- [x] API signatures: linear algebra  (_status: first set of functions merged, others like `svd` and `qr` TODO_)
- [x] API signatures: sorting  (_status: under review_)
- [x] API signatures: searching  (_status: merged_)
- [x] Accuracy (_status: under review_)
- [x] Methodology: data on existing API design & usage (_status: under review_)

_Aug 24_:

- [x] ~Array duck typing~
- [ ] API signatures: array creation (_status: gh-35 merged, a few functions (mainly `meshgrid`) to be added_)
- [x] API signatures: array manipulation (_status: under review_)
- [x] API signatures: set functions (_status: under review_)
- [x] API signatures: logical functions (_status: merged_)
- [x] C API (_status: WIP content in issue gh-51_)
- [x] Use cases (_status: merged_)
- [x] Assumptions (_status: merged_)
- [x] API signatures: math, non element-wise

_Aug 31_:

- [x] Array object (_status: gh-53 for review_)
- [x] Future API standard evolution (_status: under review, see gh-37_; for the actual process see https://github.com/data-apis/workgroup/issues/22)
- [x] Parallelism (_status: gh-61 for review_)
- [x] Data interchange mechanisms (see gh-34)
- [x] Verification - test suite (_status: merged_)
- [x] API: constants (_status: merged_)
- [x] versioning (_status: under review, see gh-37_)

_Added later_:

- [x] Python operators, and equivalent dunder methods and library functions/methods (see gh-9)
- [ ] Device support (see gh-39)
