### ISSUE TITLE
Convert the specification files to rst format

### ISSUE THREAD

**Issue by steff456** [data-apis/array-api#283]
The main goal is to make the specification files more machine readable and enable sphinx extensions like latex to convert into a pdf. This issue will track the changes by markdown file,

# API Specification
- [x] array_object.md - PR #345
- [x] broadcasting.md - PR #346
- [x] constants.md - PR #347
- [x] creation_functions.md - PR #348
- [x] data_type_functions.md - PR #349
- [x] data_types.md - PR #350
- [x] elementwise_functions.md - PR #351
- [x] function_and_method_signatures.md - PR #352
- [x] indexing.md - PR #353
- [x] manipulation_functions.md - PR #354
- [x] linear_algebra_functions.md - PR #367
- [x] searching_functions.md - PR #368 
- [x] set_functions.md - PR #369
- [x] sorting_functions.md - PR #333 
- [x] statistical_functions.md - PR #370 
- [x] type_promotion.md - PR #371 
- [x] utility_functions.md - PR #372

# Design topics

- [x] C_API.md - PR #374
- [x] accuracy.md - PR #375
- [x] copies_views_and_mutation.md - PR #376 
- [x] data_dependent_output_shapes.md - PR #377 
- [x] data_interchange.md - PR #378 
- [x] device_support.md - PR #379 
- [x] parallelism.md - PR #380 
- [x] static_typing.md - PR #381 

# Extensions
- [x] linear_algebra_functions.md - PR #384

**Comment by kgryte** [comment]
@steff456 Now that this tracking issue is complete, can we close this out?

**Comment by steff456** [comment]
I'm closing this issue given that all the specification is now in rst 🎉🎉🎉
